//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchParameter()
        {
            this.BatchParameter1 = new HashSet<BatchParameter>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string ParameterType { get; set; }
        public string ParameterSubType { get; set; }
        public string Value { get; set; }
        public string Scaled { get; set; }
        public string ScaleReference { get; set; }
        public Nullable<int> Parameter { get; set; }
        public Nullable<int> BatchListEntry { get; set; }
        public Nullable<int> Formula { get; set; }
        public Nullable<int> RecipeElement { get; set; }
    
        public virtual BatchListEntry BatchListEntry1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchParameter> BatchParameter1 { get; set; }
        public virtual BatchParameter BatchParameter2 { get; set; }
        public virtual BatchValue BatchValue { get; set; }
        public virtual Formula Formula1 { get; set; }
        public virtual RecipeElement RecipeElement1 { get; set; }
    }
}
