//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchEquipmentRequirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchEquipmentRequirement()
        {
            this.Constraint = new HashSet<Constraint>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> MasterRecipe { get; set; }
        public Nullable<int> ControlRecipe { get; set; }
        public Nullable<int> RecipeElement { get; set; }
    
        public virtual ControlRecipe ControlRecipe1 { get; set; }
        public virtual MasterRecipe MasterRecipe1 { get; set; }
        public virtual RecipeElement RecipeElement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constraint> Constraint { get; set; }
    }
}
