//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchOtherInformation
    {
        public int ID { get; set; }
        public string BatchValue { get; set; }
        public string Description { get; set; }
        public Nullable<int> MasterRecipe { get; set; }
        public Nullable<int> ControlRecipe { get; set; }
        public Nullable<int> RecipeElement { get; set; }
    
        public virtual BatchValue BatchValue1 { get; set; }
        public virtual ControlRecipe ControlRecipe1 { get; set; }
        public virtual MasterRecipe MasterRecipe1 { get; set; }
        public virtual RecipeElement RecipeElement1 { get; set; }
    }
}
