//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchProductionRecordEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchProductionRecordEntry()
        {
            this.BatchProductionRecord = new HashSet<BatchProductionRecord>();
            this.Change = new HashSet<Change>();
            this.Comment = new HashSet<Comment>();
            this.ControlRecipeRecord = new HashSet<ControlRecipeRecord>();
            this.DataSet = new HashSet<DataSet>();
            this.Event = new HashSet<Event>();
            this.MasterRecipeRecord = new HashSet<MasterRecipeRecord>();
            this.OperationsDefinitionRecord = new HashSet<OperationsDefinitionRecord>();
            this.OperationsPerformanceRecord = new HashSet<OperationsPerformanceRecord>();
            this.OperationsSceduleRecord = new HashSet<OperationsSceduleRecord>();
            this.PersonnelIdentificationManifest = new HashSet<PersonnelIdentificationManifest>();
            this.ProductDefinitionRecord = new HashSet<ProductDefinitionRecord>();
            this.ProductionPerformanceRecord = new HashSet<ProductionPerformanceRecord>();
            this.ProductionSceduleRecord = new HashSet<ProductionSceduleRecord>();
            this.RecipeElementRecord = new HashSet<RecipeElementRecord>();
            this.ResourceQualificationsManifest = new HashSet<ResourceQualificationsManifest>();
            this.Sample = new HashSet<Sample>();
            this.SampleTest = new HashSet<SampleTest>();
            this.SampleTestResult = new HashSet<SampleTestResult>();
            this.WorkDirectiveRecord = new HashSet<WorkDirectiveRecord>();
            this.WorkMasterRecord = new HashSet<WorkMasterRecord>();
            this.WorkPerformanceRecord = new HashSet<WorkPerformanceRecord>();
            this.WorkSceduleRecord = new HashSet<WorkSceduleRecord>();
        }
    
        public int EntryID { get; set; }
        public string ObjectType { get; set; }
        public Nullable<System.DateTimeOffset> TimeStamp { get; set; }
        public string ExternalReference { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProductionRecord> BatchProductionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Change> Change { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlRecipeRecord> ControlRecipeRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataSet> DataSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterRecipeRecord> MasterRecipeRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsDefinitionRecord> OperationsDefinitionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsPerformanceRecord> OperationsPerformanceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsSceduleRecord> OperationsSceduleRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelIdentificationManifest> PersonnelIdentificationManifest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDefinitionRecord> ProductDefinitionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionPerformanceRecord> ProductionPerformanceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionSceduleRecord> ProductionSceduleRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeElementRecord> RecipeElementRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceQualificationsManifest> ResourceQualificationsManifest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample> Sample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleTest> SampleTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleTestResult> SampleTestResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDirectiveRecord> WorkDirectiveRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkMasterRecord> WorkMasterRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPerformanceRecord> WorkPerformanceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSceduleRecord> WorkSceduleRecord { get; set; }
    }
}
