//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassInstanceAssociation
    {
        public int ID { get; set; }
        public int ClassEquipmentID { get; set; }
        public int MemberEquipmentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> EquipmentElement { get; set; }
    
        public virtual EquipmentElement EquipmentElement1 { get; set; }
        public virtual EquipmentProoceduralElement EquipmentProoceduralElement { get; set; }
        public virtual EquipmentProoceduralElementClass EquipmentProoceduralElementClass { get; set; }
    }
}
