//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectedLink
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> FromID { get; set; }
        public Nullable<int> ToID { get; set; }
        public Nullable<int> ProcessElement { get; set; }
    
        public virtual FromID FromID1 { get; set; }
        public virtual ProcessElement ProcessElement1 { get; set; }
        public virtual ToID ToID1 { get; set; }
    }
}
