//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enumeration
    {
        public int ID { get; set; }
        public Nullable<int> EnumerationSetID { get; set; }
        public string EnumerationNumber { get; set; }
        public string EnumerationString { get; set; }
        public string Description { get; set; }
    
        public virtual EnumerationSet EnumerationSet { get; set; }
    }
}
