//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentSpecificationProperty
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> EquipmentSpecification { get; set; }
        public Nullable<int> OpEquipmentSpecification { get; set; }
    
        public virtual EquipmentSpecification EquipmentSpecification1 { get; set; }
        public virtual OpEquipmentSpecification OpEquipmentSpecification1 { get; set; }
    }
}
