//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentElement()
        {
            this.ClassInstanceAssociation = new HashSet<ClassInstanceAssociation>();
            this.EquipmentConnection = new HashSet<EquipmentConnection>();
            this.EquipmentElement11 = new HashSet<EquipmentElement>();
            this.EquipmentElementProperty = new HashSet<EquipmentElementProperty>();
            this.EquipmentProoceduralElement = new HashSet<EquipmentProoceduralElement>();
            this.EquipmentProoceduralElementClass = new HashSet<EquipmentProoceduralElementClass>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string EquipmentElementType { get; set; }
        public string EquipmentElementLevel { get; set; }
        public int EquipmentElement1 { get; set; }
        public int EquipmentElementID { get; set; }
        public Nullable<int> BatchInformation { get; set; }
    
        public virtual BatchInformation BatchInformation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassInstanceAssociation> ClassInstanceAssociation { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentConnection> EquipmentConnection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentElement> EquipmentElement11 { get; set; }
        public virtual EquipmentElement EquipmentElement2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentElementProperty> EquipmentElementProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentProoceduralElement> EquipmentProoceduralElement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentProoceduralElementClass> EquipmentProoceduralElementClass { get; set; }
    }
}
