//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentProoceduralElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentProoceduralElement()
        {
            this.ClassInstanceAssociation = new HashSet<ClassInstanceAssociation>();
            this.EquipmentProoceduralElement1 = new HashSet<EquipmentProoceduralElement>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public int EquipmentProceduralElementType { get; set; }
        public Nullable<int> EquipmentProoceduralElementClass { get; set; }
        public string Parameter { get; set; }
        public Nullable<int> EquipmentElement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassInstanceAssociation> ClassInstanceAssociation { get; set; }
        public virtual EquipmentElement EquipmentElement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentProoceduralElement> EquipmentProoceduralElement1 { get; set; }
        public virtual EquipmentProoceduralElement EquipmentProoceduralElement2 { get; set; }
        public virtual EquipmentProoceduralElementClass EquipmentProoceduralElementClass1 { get; set; }
    }
}
