//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentProperty()
        {
            this.EquipmentProperty11 = new HashSet<EquipmentProperty>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<int> EquipmentProperty1 { get; set; }
        public string EquipmentCapabilityTestSpecification { get; set; }
        public string TestResult { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> ClassPropertyID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual EquipmentCapabilityTestSpecification EquipmentCapabilityTestSpecification1 { get; set; }
        public virtual EquipmentClassProperty EquipmentClassProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentProperty> EquipmentProperty11 { get; set; }
        public virtual EquipmentProperty EquipmentProperty2 { get; set; }
    }
}
