//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentSpecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentSpecification()
        {
            this.EquipmentSpecificationProperty = new HashSet<EquipmentSpecificationProperty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ProductSegmentID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ProductSegment ProductSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSpecificationProperty> EquipmentSpecificationProperty { get; set; }
    }
}
