//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentSegmentSpecificationProperty
    {
        public string ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> EquipmentSegmentSpecification { get; set; }
    
        public virtual EquipmentSegmentSpecification EquipmentSegmentSpecification1 { get; set; }
    }
}
