//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.AlarmData = new HashSet<AlarmData>();
            this.BatchProductionRecord = new HashSet<BatchProductionRecord>();
            this.Event1 = new HashSet<Event>();
            this.UserAttribute = new HashSet<UserAttribute>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BatchProductionRecordEntry { get; set; }
        public string EventType { get; set; }
        public string EventSubType { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string Value { get; set; }
        public string PreviousValue { get; set; }
        public string MessageText { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> ComputerID { get; set; }
        public Nullable<int> PhysicalAssetID { get; set; }
        public string ProceduralElementReference { get; set; }
        public string Category { get; set; }
        public Nullable<int> AssociatedEventID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmData> AlarmData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProductionRecord> BatchProductionRecord { get; set; }
        public virtual BatchProductionRecordEntry BatchProductionRecordEntry1 { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event1 { get; set; }
        public virtual Event Event2 { get; set; }
        public virtual Person Person { get; set; }
        public virtual PhysicalAsset PhysicalAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAttribute> UserAttribute { get; set; }
    }
}
