//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRecipeProductInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRecipeProductInformation()
        {
            this.BatchListEntry = new HashSet<BatchListEntry>();
            this.Header = new HashSet<Header>();
        }
    
        public int ProductID { get; set; }
        public string Description { get; set; }
        public string ProductName { get; set; }
        public string BatchSize { get; set; }
        public Nullable<int> GRecipeHeader { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchListEntry> BatchListEntry { get; set; }
        public virtual BatchSize BatchSize1 { get; set; }
        public virtual GRecipeHeader GRecipeHeader1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Header> Header { get; set; }
    }
}
