//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRecipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRecipe()
        {
            this.BatchListEntry = new HashSet<BatchListEntry>();
            this.OtherInformation = new HashSet<OtherInformation>();
            this.ResourceConstraint = new HashSet<ResourceConstraint>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string GRecipeType { get; set; }
        public string LifeCycleState { get; set; }
        public Nullable<int> Header { get; set; }
        public Nullable<int> Formula { get; set; }
        public string ProcessProcedure { get; set; }
        public Nullable<int> GRecipeInformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchListEntry> BatchListEntry { get; set; }
        public virtual GRecipeFormula GRecipeFormula { get; set; }
        public virtual GRecipeHeader GRecipeHeader { get; set; }
        public virtual GRecipeInformation GRecipeInformation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherInformation> OtherInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceConstraint> ResourceConstraint { get; set; }
    }
}
