//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRecipeHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRecipeHeader()
        {
            this.GRecipe = new HashSet<GRecipe>();
            this.GRecipeProductInformation = new HashSet<GRecipeProductInformation>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string DerivedFromID { get; set; }
        public Nullable<System.DateTimeOffset> EffectiveDate { get; set; }
        public Nullable<System.DateTimeOffset> ExpirationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRecipe> GRecipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRecipeProductInformation> GRecipeProductInformation { get; set; }
        public virtual HeaderProperty HeaderProperty { get; set; }
    }
}
