//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderProperty
    {
        public int HeaderID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
    
        public virtual GRecipeHeader GRecipeHeader { get; set; }
        public virtual Value Value1 { get; set; }
    }
}
