//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individualapproval
    {
        public int ID { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTimeOffset> ApprovalDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> ApprovalHistory { get; set; }
    
        public virtual ApprovalHistory ApprovalHistory1 { get; set; }
    }
}
