//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobOrder()
        {
            this.JobResponse = new HashSet<JobResponse>();
            this.OpEquipmentRequirement = new HashSet<OpEquipmentRequirement>();
            this.OpMaterialRequirement = new HashSet<OpMaterialRequirement>();
            this.OpPersonnelRequirement = new HashSet<OpPersonnelRequirement>();
            this.OpPhysicalAssetRequirement = new HashSet<OpPhysicalAssetRequirement>();
            this.Parameter = new HashSet<Parameter>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public string WorkType { get; set; }
        public int WorkMasterID { get; set; }
        public string WorkMasterVersion { get; set; }
        public Nullable<System.DateTimeOffset> StartTime { get; set; }
        public Nullable<System.DateTimeOffset> EndTime { get; set; }
        public string Priority { get; set; }
        public string Command { get; set; }
        public string CommandRule { get; set; }
        public string DispatchStatus { get; set; }
        public Nullable<int> WorkRequest { get; set; }
        public Nullable<int> JobList { get; set; }
    
        public virtual JobList JobList1 { get; set; }
        public virtual WorkMaster WorkMaster { get; set; }
        public virtual WorkRequest WorkRequest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobResponse> JobResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpEquipmentRequirement> OpEquipmentRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialRequirement> OpMaterialRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPersonnelRequirement> OpPersonnelRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetRequirement> OpPhysicalAssetRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parameter> Parameter { get; set; }
    }
}
