//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobResponsetData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobResponsetData()
        {
            this.OpSegmentData = new HashSet<OpSegmentData>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public string RequiredByRequestedSegment { get; set; }
        public Nullable<int> JobResponse { get; set; }
    
        public virtual JobResponse JobResponse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpSegmentData> OpSegmentData { get; set; }
    }
}
