//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobResponse()
        {
            this.JobResponse11 = new HashSet<JobResponse>();
            this.JobResponsetData = new HashSet<JobResponsetData>();
            this.OpEquipmentActual = new HashSet<OpEquipmentActual>();
            this.OpMaterialActual = new HashSet<OpMaterialActual>();
            this.OpPersonnelActual = new HashSet<OpPersonnelActual>();
            this.OpPhysicalAssetActual = new HashSet<OpPhysicalAssetActual>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string WorkType { get; set; }
        public Nullable<int> JobOrderID { get; set; }
        public Nullable<int> WorkDirectiveID { get; set; }
        public string WorkDirectiveVersion { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string JobState { get; set; }
        public Nullable<int> JobResponse1 { get; set; }
        public Nullable<int> WorkResponse { get; set; }
    
        public virtual JobOrder JobOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobResponse> JobResponse11 { get; set; }
        public virtual JobResponse JobResponse2 { get; set; }
        public virtual WorkDirective WorkDirective { get; set; }
        public virtual WorkResponse WorkResponse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobResponsetData> JobResponsetData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpEquipmentActual> OpEquipmentActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialActual> OpMaterialActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPersonnelActual> OpPersonnelActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetActual> OpPhysicalAssetActual { get; set; }
    }
}
