//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KEP_logger
    {
        public int id { get; set; }
        public Nullable<int> Controller_ID { get; set; }
        public Nullable<float> Weight_VALUE { get; set; }
        public Nullable<System.DateTimeOffset> Weight_TIMESTAMP { get; set; }
        public Nullable<bool> WEIGHT_OK_VALUE { get; set; }
    }
}
