//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIInstanceTimeRange
    {
        public int ID { get; set; }
        public Nullable<System.DateTimeOffset> StartTime { get; set; }
        public Nullable<System.DateTimeOffset> EndTime { get; set; }
        public string Recurrence { get; set; }
        public string Duration { get; set; }
        public Nullable<int> KPIInstanceID { get; set; }
    
        public virtual KPIInstance KPIInstance { get; set; }
    }
}
