//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPIInstance()
        {
            this.KPIInstanceProperty = new HashSet<KPIInstanceProperty>();
            this.KPIInstanceRange = new HashSet<KPIInstanceRange>();
            this.KPIInstanceResourceReference = new HashSet<KPIInstanceResourceReference>();
            this.KPIInstanceTimeRange = new HashSet<KPIInstanceTimeRange>();
            this.KPIValue = new HashSet<KPIValue>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Formula { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Trend { get; set; }
        public string Timing { get; set; }
        public string Audience { get; set; }
        public string ProductionMethodology { get; set; }
        public string EffectModel { get; set; }
        public string Notes { get; set; }
        public Nullable<int> KPIDefinitionID { get; set; }
    
        public virtual KPIDefinition KPIDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIInstanceProperty> KPIInstanceProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIInstanceRange> KPIInstanceRange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIInstanceResourceReference> KPIInstanceResourceReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIInstanceTimeRange> KPIInstanceTimeRange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIValue> KPIValue { get; set; }
    }
}
