//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListHeader()
        {
            this.ModificationLog = new HashSet<ModificationLog>();
        }
    
        public int ID { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public string Origin { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> BatchList { get; set; }
        public Nullable<int> BatchInformation { get; set; }
    
        public virtual BatchInformation BatchInformation1 { get; set; }
        public virtual BatchList BatchList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModificationLog> ModificationLog { get; set; }
    }
}
