//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturingBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManufacturingBill()
        {
            this.ManufacturingBill1 = new HashSet<ManufacturingBill>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> MaterialClassID { get; set; }
        public Nullable<int> MaterialDefinitionID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> AssemblyManufacturingBill { get; set; }
        public string AssemblyType { get; set; }
        public string AssemblyRelationship { get; set; }
        public string BillOfMaterialID { get; set; }
        public Nullable<int> ProductDefinition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturingBill> ManufacturingBill1 { get; set; }
        public virtual ManufacturingBill ManufacturingBill2 { get; set; }
        public virtual MaterialClass MaterialClass { get; set; }
        public virtual MaterialDefinition MaterialDefinition { get; set; }
        public virtual ProductDefinition ProductDefinition1 { get; set; }
    }
}
