//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialDefinitionAssemblies
    {
        public int MaterialDefinitionID { get; set; }
        public int AssemblyDefinitionID { get; set; }
        public string AssemblyType { get; set; }
        public string AssemblyRelationship { get; set; }
    
        public virtual MaterialDefinition MaterialDefinition { get; set; }
        public virtual MaterialDefinition MaterialDefinition1 { get; set; }
    }
}
