//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInformation
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public string PublishedDate { get; set; }
        public Nullable<int> MaterialClassID { get; set; }
        public Nullable<int> MaterialDefinition { get; set; }
        public Nullable<int> MaterialLot { get; set; }
        public Nullable<int> MaterialSubLot { get; set; }
    
        public virtual MaterialClass MaterialClass { get; set; }
        public virtual MaterialDefinition MaterialDefinition1 { get; set; }
        public virtual MaterialLot MaterialLot1 { get; set; }
        public virtual MaterialSubLot MaterialSubLot1 { get; set; }
    }
}
