//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialDefinitionLinks
    {
        public int MaterialDefinition1 { get; set; }
        public int MaterialDefinition2 { get; set; }
        public Nullable<int> LinkType { get; set; }
    
        public virtual MaterialDefinition MaterialDefinition { get; set; }
        public virtual MaterialDefinition MaterialDefinition3 { get; set; }
        public virtual MaterialLinkTypes MaterialLinkTypes { get; set; }
    }
}
