//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSubLotLinks
    {
        public int MateriaSubLot1 { get; set; }
        public int MateriaSubLot2 { get; set; }
        public Nullable<int> LinkType { get; set; }
    
        public virtual MaterialLinkTypes MaterialLinkTypes { get; set; }
        public virtual MaterialSubLot MaterialSubLot { get; set; }
        public virtual MaterialSubLot MaterialSubLot1 { get; set; }
    }
}
