//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialCapability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialCapability()
        {
            this.MaterialCapability1 = new HashSet<MaterialCapability>();
            this.MaterialCapabilityProperty = new HashSet<MaterialCapabilityProperty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MaterialDefinitionID { get; set; }
        public Nullable<int> MaterialLotID { get; set; }
        public Nullable<int> MaterialSubLotID { get; set; }
        public string Description { get; set; }
        public string CapabilityType { get; set; }
        public string Reason { get; set; }
        public string EquipmentElementLevel { get; set; }
        public string MaterialUse { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Location { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> AssemblyCapability { get; set; }
        public string AssemblyType { get; set; }
        public string AssemblyRealationship { get; set; }
        public Nullable<int> ProcessSegmentCapabilityID { get; set; }
        public Nullable<int> ProductionCapability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialCapability> MaterialCapability1 { get; set; }
        public virtual MaterialCapability MaterialCapability2 { get; set; }
        public virtual MaterialDefinition MaterialDefinition { get; set; }
        public virtual MaterialLot MaterialLot { get; set; }
        public virtual MaterialSubLot MaterialSubLot { get; set; }
        public virtual ProcessSegmentCapability ProcessSegmentCapability { get; set; }
        public virtual ProductionCapability ProductionCapability1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialCapabilityProperty> MaterialCapabilityProperty { get; set; }
    }
}
