//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialClassLinks
    {
        public int MaterialClassID1 { get; set; }
        public int MaterialClassID2 { get; set; }
        public int LinkType { get; set; }
    
        public virtual MaterialClass MaterialClass { get; set; }
        public virtual MaterialClass MaterialClass1 { get; set; }
        public virtual MaterialLinkTypes MaterialLinkTypes { get; set; }
    }
}
