//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialDefinition()
        {
            this.BatchProductionRecord = new HashSet<BatchProductionRecord>();
            this.ConsumableActual = new HashSet<ConsumableActual>();
            this.ConsumableExpectedRequirement = new HashSet<ConsumableExpectedRequirement>();
            this.GRecipeMaterial = new HashSet<GRecipeMaterial>();
            this.ManufacturingBill = new HashSet<ManufacturingBill>();
            this.MaterialActual = new HashSet<MaterialActual>();
            this.MaterialCapability = new HashSet<MaterialCapability>();
            this.MaterialConsumedActual = new HashSet<MaterialConsumedActual>();
            this.MaterialConsumedRequirement = new HashSet<MaterialConsumedRequirement>();
            this.MaterialDefinitionAssemblies = new HashSet<MaterialDefinitionAssemblies>();
            this.MaterialDefinitionAssemblies1 = new HashSet<MaterialDefinitionAssemblies>();
            this.MaterialDefinitionLinks = new HashSet<MaterialDefinitionLinks>();
            this.MaterialDefinitionLinks1 = new HashSet<MaterialDefinitionLinks>();
            this.MaterialDefinitionProperty = new HashSet<MaterialDefinitionProperty>();
            this.MaterialInformation = new HashSet<MaterialInformation>();
            this.MaterialLot = new HashSet<MaterialLot>();
            this.MaterialProducedActual = new HashSet<MaterialProducedActual>();
            this.MaterialProducedRequirement = new HashSet<MaterialProducedRequirement>();
            this.MaterialRequirement = new HashSet<MaterialRequirement>();
            this.MaterialSegmentSpecificftion = new HashSet<MaterialSegmentSpecificftion>();
            this.MaterialSpecification = new HashSet<MaterialSpecification>();
            this.OperationsMaterialBillItem = new HashSet<OperationsMaterialBillItem>();
            this.OpMaterialActual = new HashSet<OpMaterialActual>();
            this.OpMaterialCapability = new HashSet<OpMaterialCapability>();
            this.OpMaterialRequirement = new HashSet<OpMaterialRequirement>();
            this.OpMaterialSpecification = new HashSet<OpMaterialSpecification>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProductionRecord> BatchProductionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumableActual> ConsumableActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumableExpectedRequirement> ConsumableExpectedRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRecipeMaterial> GRecipeMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturingBill> ManufacturingBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialActual> MaterialActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialCapability> MaterialCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialConsumedActual> MaterialConsumedActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialConsumedRequirement> MaterialConsumedRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialDefinitionAssemblies> MaterialDefinitionAssemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialDefinitionAssemblies> MaterialDefinitionAssemblies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialDefinitionLinks> MaterialDefinitionLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialDefinitionLinks> MaterialDefinitionLinks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialDefinitionProperty> MaterialDefinitionProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialInformation> MaterialInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialLot> MaterialLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProducedActual> MaterialProducedActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProducedRequirement> MaterialProducedRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialRequirement> MaterialRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSegmentSpecificftion> MaterialSegmentSpecificftion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSpecification> MaterialSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsMaterialBillItem> OperationsMaterialBillItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialActual> OpMaterialActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialCapability> OpMaterialCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialRequirement> OpMaterialRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialSpecification> OpMaterialSpecification { get; set; }
    }
}
