//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificationLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDate { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public Nullable<int> ListHeader { get; set; }
        public Nullable<int> Header { get; set; }
    
        public virtual Header Header1 { get; set; }
        public virtual ListHeader ListHeader1 { get; set; }
    }
}
