//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpEquipmentActual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpEquipmentActual()
        {
            this.EquipmentActualProperty = new HashSet<EquipmentActualProperty>();
        }
    
        public int ID { get; set; }
        public int EquipmentClassID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string Description { get; set; }
        public string EquipmentUse { get; set; }
        public int Quantity { get; set; }
        public string HierarchyScope { get; set; }
        public string RequiredByRequestedSegment { get; set; }
        public Nullable<int> JobResponseID { get; set; }
        public Nullable<int> SegmentResponseID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentActualProperty> EquipmentActualProperty { get; set; }
        public virtual EquipmentClass EquipmentClass { get; set; }
        public virtual JobResponse JobResponse { get; set; }
        public virtual OpSegmentResponse OpSegmentResponse { get; set; }
    }
}
