//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpEquipmentRequirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpEquipmentRequirement()
        {
            this.EquipmentRequirementProperty = new HashSet<EquipmentRequirementProperty>();
        }
    
        public int ID { get; set; }
        public int EquipmentID { get; set; }
        public string Description { get; set; }
        public string EquipmentUse { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string EquipmentLevel { get; set; }
        public string RequiredByRequestedSegment { get; set; }
        public Nullable<int> JobOrderID { get; set; }
        public Nullable<int> SegmenRequirementID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentRequirementProperty> EquipmentRequirementProperty { get; set; }
        public virtual JobOrder JobOrder { get; set; }
        public virtual OpSegmentRequirement OpSegmentRequirement { get; set; }
    }
}
