//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationsRequest()
        {
            this.OpSegmentRequirement = new HashSet<OpSegmentRequirement>();
            this.OpSegmentResponse = new HashSet<OpSegmentResponse>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public string OperationsType { get; set; }
        public Nullable<System.DateTimeOffset> StartTime { get; set; }
        public Nullable<System.DateTimeOffset> EndTime { get; set; }
        public string Priority { get; set; }
        public Nullable<int> OperationsDefinitionID { get; set; }
        public string RequestState { get; set; }
        public Nullable<int> OperationsSchedule { get; set; }
        public Nullable<int> OperationsResponse { get; set; }
    
        public virtual OperationsDefinition OperationsDefinition { get; set; }
        public virtual OperationsResponse OperationsResponse1 { get; set; }
        public virtual OperationsScedule OperationsScedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpSegmentRequirement> OpSegmentRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpSegmentResponse> OpSegmentResponse { get; set; }
    }
}
