//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsMaterialBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationsMaterialBill()
        {
            this.OperationsMaterialBillItem = new HashSet<OperationsMaterialBillItem>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> OperationsDefinition { get; set; }
    
        public virtual OperationsDefinition OperationsDefinition1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsMaterialBillItem> OperationsMaterialBillItem { get; set; }
    }
}
