//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsDefinitionInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationsDefinitionInformation()
        {
            this.OperationsDefinition = new HashSet<OperationsDefinition>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsDefinition> OperationsDefinition { get; set; }
    }
}
