//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationsDefinition()
        {
            this.OperationsDefinitionRecord = new HashSet<OperationsDefinitionRecord>();
            this.OperationsMaterialBill = new HashSet<OperationsMaterialBill>();
            this.OperationsRequest = new HashSet<OperationsRequest>();
            this.OperationsSegment = new HashSet<OperationsSegment>();
            this.OpSegmentRequirement = new HashSet<OpSegmentRequirement>();
            this.WorkDefinition = new HashSet<WorkDefinition>();
        }
    
        public int ID { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public string OperationsType { get; set; }
        public Nullable<System.DateTimeOffset> PublishedDate { get; set; }
        public string BillOfMaterialsID { get; set; }
        public string BillOfResourcesID { get; set; }
        public Nullable<int> OperationsResponse { get; set; }
        public Nullable<int> OpSegmentResponse { get; set; }
        public Nullable<int> OperationsDefinitionInformation { get; set; }
    
        public virtual OperationsDefinitionInformation OperationsDefinitionInformation1 { get; set; }
        public virtual OperationsResponse OperationsResponse1 { get; set; }
        public virtual OpSegmentResponse OpSegmentResponse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsDefinitionRecord> OperationsDefinitionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsMaterialBill> OperationsMaterialBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsRequest> OperationsRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsSegment> OperationsSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpSegmentRequirement> OpSegmentRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDefinition> WorkDefinition { get; set; }
    }
}
