//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsSegment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationsSegment()
        {
            this.OpEquipmentSpecification = new HashSet<OpEquipmentSpecification>();
            this.OperationsSegment11 = new HashSet<OperationsSegment>();
            this.OpMaterialSpecification = new HashSet<OpMaterialSpecification>();
            this.OpPersonnelSpecification = new HashSet<OpPersonnelSpecification>();
            this.OpPhysicalAssetSpecification = new HashSet<OpPhysicalAssetSpecification>();
            this.ProcessSegment = new HashSet<ProcessSegment>();
            this.SegmentParameter = new HashSet<SegmentParameter>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string OperationsType { get; set; }
        public string Duration { get; set; }
        public string SegmentDependency { get; set; }
        public Nullable<int> OperationsSegment1 { get; set; }
        public Nullable<int> OperationsDefinitionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpEquipmentSpecification> OpEquipmentSpecification { get; set; }
        public virtual OperationsDefinition OperationsDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsSegment> OperationsSegment11 { get; set; }
        public virtual OperationsSegment OperationsSegment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialSpecification> OpMaterialSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPersonnelSpecification> OpPersonnelSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetSpecification> OpPhysicalAssetSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessSegment> ProcessSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentParameter> SegmentParameter { get; set; }
    }
}
