//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpMaterialSpecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpMaterialSpecification()
        {
            this.MaterialSpecificationProperty = new HashSet<MaterialSpecificationProperty>();
            this.OperationsMaterialBillItem = new HashSet<OperationsMaterialBillItem>();
            this.OpMaterialSpecification1 = new HashSet<OpMaterialSpecification>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MaterialDefinitionID { get; set; }
        public string Description { get; set; }
        public string MaterialUse { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> AssemblySpecification { get; set; }
        public string AssemblyType { get; set; }
        public string AssemblyRelationship { get; set; }
        public Nullable<int> OperationsSegment { get; set; }
        public Nullable<int> WorkDefinition { get; set; }
    
        public virtual MaterialDefinition MaterialDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSpecificationProperty> MaterialSpecificationProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsMaterialBillItem> OperationsMaterialBillItem { get; set; }
        public virtual OperationsSegment OperationsSegment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialSpecification> OpMaterialSpecification1 { get; set; }
        public virtual OpMaterialSpecification OpMaterialSpecification2 { get; set; }
        public virtual WorkDefinition WorkDefinition1 { get; set; }
    }
}
