//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpMaterialActual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpMaterialActual()
        {
            this.MaterialActualProperty = new HashSet<MaterialActualProperty>();
            this.OpMaterialActual1 = new HashSet<OpMaterialActual>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MaterialClassID { get; set; }
        public int MaterialDefinitionID { get; set; }
        public int MaterialLotID { get; set; }
        public Nullable<int> MaterialSubLotID { get; set; }
        public string Description { get; set; }
        public string MaterialUse { get; set; }
        public string StorageLocation { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> AssemblyActual { get; set; }
        public string AssemblyType { get; set; }
        public string AssemblyRelationship { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public string RequiredByRequestedSegment { get; set; }
        public Nullable<int> SegmentResponseID { get; set; }
        public Nullable<int> JobResponseID { get; set; }
    
        public virtual JobResponse JobResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialActualProperty> MaterialActualProperty { get; set; }
        public virtual MaterialClass MaterialClass { get; set; }
        public virtual MaterialDefinition MaterialDefinition { get; set; }
        public virtual MaterialLot MaterialLot { get; set; }
        public virtual MaterialSubLot MaterialSubLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialActual> OpMaterialActual1 { get; set; }
        public virtual OpMaterialActual OpMaterialActual2 { get; set; }
        public virtual OpSegmentResponse OpSegmentResponse { get; set; }
    }
}
