//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpPersonnelCapability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpPersonnelCapability()
        {
            this.PersonnelCapabilityProperty = new HashSet<PersonnelCapabilityProperty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Description { get; set; }
        public string CapabilityType { get; set; }
        public string Reason { get; set; }
        public string ConfidenceFactor { get; set; }
        public string PersonnelUse { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> OperationCapabilityID { get; set; }
        public Nullable<int> ProcessSegmentCapabilityID { get; set; }
        public Nullable<int> WorkCapabilityID { get; set; }
        public Nullable<int> WorkMasterCapabilityID { get; set; }
    
        public virtual OperationsCapability OperationsCapability { get; set; }
        public virtual Person Person { get; set; }
        public virtual OpProcessSegmentCapability OpProcessSegmentCapability { get; set; }
        public virtual WorkCapability WorkCapability { get; set; }
        public virtual WorkMasterCapability WorkMasterCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelCapabilityProperty> PersonnelCapabilityProperty { get; set; }
    }
}
