//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpPhysicalAssetActual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpPhysicalAssetActual()
        {
            this.PhysicalAssetActualProperty = new HashSet<PhysicalAssetActualProperty>();
        }
    
        public int ID { get; set; }
        public int PhysicalAssetClassID { get; set; }
        public int PhysicalAssetID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public string RequiredByRequestedSegment { get; set; }
        public Nullable<int> JobResponseID { get; set; }
        public Nullable<int> SegmentResponseID { get; set; }
    
        public virtual JobResponse JobResponse { get; set; }
        public virtual OpSegmentResponse OpSegmentResponse { get; set; }
        public virtual PhysicalAsset PhysicalAsset { get; set; }
        public virtual PhysicalAssetClass PhysicalAssetClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetActualProperty> PhysicalAssetActualProperty { get; set; }
    }
}
