//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpSegmentResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpSegmentResponse()
        {
            this.OpEquipmentActual = new HashSet<OpEquipmentActual>();
            this.OperationsDefinition = new HashSet<OperationsDefinition>();
            this.OpMaterialActual = new HashSet<OpMaterialActual>();
            this.OpPersonnelActual = new HashSet<OpPersonnelActual>();
            this.OpPhysicalAssetActual = new HashSet<OpPhysicalAssetActual>();
            this.OpSegmentData = new HashSet<OpSegmentData>();
            this.OpSegmentResponse1 = new HashSet<OpSegmentResponse>();
            this.ProcessSegment = new HashSet<ProcessSegment>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string OperationsType { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public string SegmentState { get; set; }
        public Nullable<int> SegmentResponse { get; set; }
        public string RequiredByRequestedSegment { get; set; }
        public Nullable<int> OperationsResponse { get; set; }
        public Nullable<int> OperationsRequested { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpEquipmentActual> OpEquipmentActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsDefinition> OperationsDefinition { get; set; }
        public virtual OperationsRequest OperationsRequest { get; set; }
        public virtual OperationsResponse OperationsResponse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialActual> OpMaterialActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPersonnelActual> OpPersonnelActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetActual> OpPhysicalAssetActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpSegmentData> OpSegmentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpSegmentResponse> OpSegmentResponse1 { get; set; }
        public virtual OpSegmentResponse OpSegmentResponse2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessSegment> ProcessSegment { get; set; }
    }
}
