//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parameter()
        {
            this.Parameter11 = new HashSet<Parameter>();
        }
    
        public int ID { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public Nullable<int> Parameter1 { get; set; }
        public Nullable<int> JobOrder { get; set; }
    
        public virtual JobOrder JobOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parameter> Parameter11 { get; set; }
        public virtual Parameter Parameter2 { get; set; }
    }
}
