//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelCapabilityProperty
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PersonnelCapabilityID { get; set; }
        public Nullable<int> OpPersonnelCapabilityID { get; set; }
    
        public virtual OpPersonnelCapability OpPersonnelCapability { get; set; }
        public virtual PersonnelCapability PersonnelCapability { get; set; }
    }
}
