//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonProperty()
        {
            this.PersonProperty11 = new HashSet<PersonProperty>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<int> PersonProperty1 { get; set; }
        public Nullable<int> QualificationTestSpecificationID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> ClassPropertyID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PersonnelClassProperty PersonnelClassProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonProperty> PersonProperty11 { get; set; }
        public virtual PersonProperty PersonProperty2 { get; set; }
        public virtual QualificationTestSpecification QualificationTestSpecification { get; set; }
    }
}
