//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalAssetClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicalAssetClass()
        {
            this.OpPhysicalAssetActual = new HashSet<OpPhysicalAssetActual>();
            this.OpPhysicalAssetCapability = new HashSet<OpPhysicalAssetCapability>();
            this.OpPhysicalAssetRequirement = new HashSet<OpPhysicalAssetRequirement>();
            this.OpPhysicalAssetSpecification = new HashSet<OpPhysicalAssetSpecification>();
            this.PhysicalAsset = new HashSet<PhysicalAsset>();
            this.PhysicalAssetActual = new HashSet<PhysicalAssetActual>();
            this.PhysicalAssetCapability = new HashSet<PhysicalAssetCapability>();
            this.PhysicalAssetClassProperty = new HashSet<PhysicalAssetClassProperty>();
            this.PhysicalAssetRequirement = new HashSet<PhysicalAssetRequirement>();
            this.PhysicalAssetSegmentSpecification = new HashSet<PhysicalAssetSegmentSpecification>();
            this.PhysicalAssetSpecification = new HashSet<PhysicalAssetSpecification>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public string Manufacturer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetActual> OpPhysicalAssetActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetCapability> OpPhysicalAssetCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetRequirement> OpPhysicalAssetRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetSpecification> OpPhysicalAssetSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAsset> PhysicalAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetActual> PhysicalAssetActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetCapability> PhysicalAssetCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetClassProperty> PhysicalAssetClassProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetRequirement> PhysicalAssetRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetSegmentSpecification> PhysicalAssetSegmentSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetSpecification> PhysicalAssetSpecification { get; set; }
    }
}
