//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalAssetSpecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicalAssetSpecification()
        {
            this.PhysicalAssetSpecificationProperty = new HashSet<PhysicalAssetSpecificationProperty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PhysicalAssetClassID { get; set; }
        public Nullable<int> PhysicalAssetID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ProductSegmentID { get; set; }
    
        public virtual PhysicalAsset PhysicalAsset { get; set; }
        public virtual PhysicalAssetClass PhysicalAssetClass { get; set; }
        public virtual ProductSegment ProductSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetSpecificationProperty> PhysicalAssetSpecificationProperty { get; set; }
    }
}
