//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalAssetProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicalAssetProperty()
        {
            this.PhysicalAssetProperty11 = new HashSet<PhysicalAssetProperty>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<int> PhysicalAssetProperty1 { get; set; }
        public string PhysicalAssetCapabilityTestSpecification { get; set; }
        public string TestResult { get; set; }
        public Nullable<int> PhysicalAssetID { get; set; }
        public Nullable<int> ClassPropertyID { get; set; }
    
        public virtual PhysicalAsset PhysicalAsset { get; set; }
        public virtual PhysicalAssetCapabilityTestSpesification PhysicalAssetCapabilityTestSpesification { get; set; }
        public virtual PhysicalAssetClassProperty PhysicalAssetClassProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetProperty> PhysicalAssetProperty11 { get; set; }
        public virtual PhysicalAssetProperty PhysicalAssetProperty2 { get; set; }
    }
}
