//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalAssetCapabilityProperty
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PhysicalAssetCapability { get; set; }
        public Nullable<int> OpPhysicalAssetCapability { get; set; }
    
        public virtual OpPhysicalAssetCapability OpPhysicalAssetCapability1 { get; set; }
        public virtual PhysicalAssetCapability PhysicalAssetCapability1 { get; set; }
    }
}
