//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicalAsset()
        {
            this.BatchProductionRecord = new HashSet<BatchProductionRecord>();
            this.Event = new HashSet<Event>();
            this.OpPhysicalAssetActual = new HashSet<OpPhysicalAssetActual>();
            this.OpPhysicalAssetCapability = new HashSet<OpPhysicalAssetCapability>();
            this.OpPhysicalAssetRequirement = new HashSet<OpPhysicalAssetRequirement>();
            this.OpPhysicalAssetSpecification = new HashSet<OpPhysicalAssetSpecification>();
            this.EquipmentAssetMapping = new HashSet<EquipmentAssetMapping>();
            this.PhysicalAsset11 = new HashSet<PhysicalAsset>();
            this.PhysicalAssetActual = new HashSet<PhysicalAssetActual>();
            this.PhysicalAssetCapability = new HashSet<PhysicalAssetCapability>();
            this.PhysicalAssetProperty = new HashSet<PhysicalAssetProperty>();
            this.PhysicalAssetRequirement = new HashSet<PhysicalAssetRequirement>();
            this.PhysicalAssetSegmentSpecification = new HashSet<PhysicalAssetSegmentSpecification>();
            this.PhysicalAssetSpecification = new HashSet<PhysicalAssetSpecification>();
            this.Sample = new HashSet<Sample>();
            this.SampleTestResult = new HashSet<SampleTestResult>();
            this.TagSpecification = new HashSet<TagSpecification>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string HierarchyScope { get; set; }
        public string PhysicalLocation { get; set; }
        public Nullable<int> FixedAssetID { get; set; }
        public string VendorID { get; set; }
        public string EquipmentLevel { get; set; }
        public Nullable<int> PhysicalAsset1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProductionRecord> BatchProductionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetActual> OpPhysicalAssetActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetCapability> OpPhysicalAssetCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetRequirement> OpPhysicalAssetRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetSpecification> OpPhysicalAssetSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentAssetMapping> EquipmentAssetMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAsset> PhysicalAsset11 { get; set; }
        public virtual PhysicalAsset PhysicalAsset2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetActual> PhysicalAssetActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetCapability> PhysicalAssetCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetProperty> PhysicalAssetProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetRequirement> PhysicalAssetRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetSegmentSpecification> PhysicalAssetSegmentSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetSpecification> PhysicalAssetSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample> Sample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleTestResult> SampleTestResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagSpecification> TagSpecification { get; set; }
    }
}
