//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessElementParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessElementParameter()
        {
            this.ProcessElementParameter11 = new HashSet<ProcessElementParameter>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProcessElementParameter1 { get; set; }
        public string Value { get; set; }
        public Nullable<int> ProcessElement { get; set; }
        public Nullable<int> GRecipeFormula { get; set; }
    
        public virtual GRecipeFormula GRecipeFormula1 { get; set; }
        public virtual ProcessElement ProcessElement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessElementParameter> ProcessElementParameter11 { get; set; }
        public virtual ProcessElementParameter ProcessElementParameter2 { get; set; }
        public virtual Value Value1 { get; set; }
    }
}
