//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDefinition()
        {
            this.ManufacturingBill = new HashSet<ManufacturingBill>();
            this.ProcessSegment = new HashSet<ProcessSegment>();
            this.ProductDefinitionRecord = new HashSet<ProductDefinitionRecord>();
            this.ProductSegment = new HashSet<ProductSegment>();
        }
    
        public int ID { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public Nullable<System.DateTimeOffset> PublishedDate { get; set; }
        public Nullable<int> ProductProductionRule { get; set; }
        public string BillOfMaterialsID { get; set; }
        public string BillOfResourcesID { get; set; }
        public Nullable<int> ProductInformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturingBill> ManufacturingBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessSegment> ProcessSegment { get; set; }
        public virtual ProductInformation ProductInformation1 { get; set; }
        public virtual ProductProductionRuleIDGroup ProductProductionRuleIDGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDefinitionRecord> ProductDefinitionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSegment> ProductSegment { get; set; }
    }
}
