//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSegment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSegment()
        {
            this.EquipmentSpecification = new HashSet<EquipmentSpecification>();
            this.MaterialSpecification = new HashSet<MaterialSpecification>();
            this.PersonnelSpecification = new HashSet<PersonnelSpecification>();
            this.PhysicalAssetSpecification = new HashSet<PhysicalAssetSpecification>();
            this.ProcessSegment = new HashSet<ProcessSegment>();
            this.ProductionParameter = new HashSet<ProductionParameter>();
            this.ProductSegment11 = new HashSet<ProductSegment>();
            this.SegmentRequirement = new HashSet<SegmentRequirement>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Duration { get; set; }
        public string SegmentDependency { get; set; }
        public Nullable<int> ProductSegment1 { get; set; }
        public Nullable<int> SegmentResponse { get; set; }
        public Nullable<int> ProductDefinition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSpecification> EquipmentSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSpecification> MaterialSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelSpecification> PersonnelSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetSpecification> PhysicalAssetSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessSegment> ProcessSegment { get; set; }
        public virtual ProductDefinition ProductDefinition1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionParameter> ProductionParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSegment> ProductSegment11 { get; set; }
        public virtual ProductSegment ProductSegment2 { get; set; }
        public virtual SegmentResponse SegmentResponse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentRequirement> SegmentRequirement { get; set; }
    }
}
