//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionResponse()
        {
            this.ProductProductionRuleIDGroup = new HashSet<ProductProductionRuleIDGroup>();
            this.SegmentResponse = new HashSet<SegmentResponse>();
        }
    
        public int ID { get; set; }
        public int ProductionRequestID { get; set; }
        public string Location { get; set; }
        public int HierarchyScope { get; set; }
        public Nullable<System.DateTimeOffset> StartTime { get; set; }
        public Nullable<System.DateTimeOffset> EndTime { get; set; }
        public string ResponseState { get; set; }
        public Nullable<int> ProductionPerfomance { get; set; }
    
        public virtual ProductionPerformance ProductionPerformance { get; set; }
        public virtual ProductionRequest ProductionRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductProductionRuleIDGroup> ProductProductionRuleIDGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentResponse> SegmentResponse { get; set; }
    }
}
