//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionData()
        {
            this.ProductionData11 = new HashSet<ProductionData>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public string RequiredByRequestedSegmentResponse { get; set; }
        public Nullable<int> ProductionData1 { get; set; }
        public Nullable<int> SegmentResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionData> ProductionData11 { get; set; }
        public virtual ProductionData ProductionData2 { get; set; }
        public virtual SegmentResponse SegmentResponse1 { get; set; }
    }
}
