//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionParameter()
        {
            this.SegmentRequirement = new HashSet<SegmentRequirement>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductSegmentID { get; set; }
        public Nullable<int> ProcessSegmentID { get; set; }
        public string Parameter { get; set; }
    
        public virtual ProcessSegment ProcessSegment { get; set; }
        public virtual ProductSegment ProductSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentRequirement> SegmentRequirement { get; set; }
    }
}
