//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceNetworkConnection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResourceNetworkConnection()
        {
            this.ResourceNetworkConnection1 = new HashSet<ResourceNetworkConnection>();
            this.ResourceNetworkConnectionType = new HashSet<ResourceNetworkConnectionType>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ResourceNetworkConnectionID { get; set; }
        public int FromResourceReference { get; set; }
        public int ToResourceReference { get; set; }
        public string ConnectionProperty { get; set; }
        public Nullable<int> ResourceRelationshipNetwork { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceNetworkConnection> ResourceNetworkConnection1 { get; set; }
        public virtual ResourceNetworkConnection ResourceNetworkConnection2 { get; set; }
        public virtual ResourceReference ResourceReference { get; set; }
        public virtual ResourceReference ResourceReference1 { get; set; }
        public virtual ResourceRelationshipNetwork ResourceRelationshipNetwork1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceNetworkConnectionType> ResourceNetworkConnectionType { get; set; }
    }
}
