//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleTestResult
    {
        public int ID { get; set; }
        public Nullable<int> BatchProductionRecordEntry { get; set; }
        public string TestDisposition { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> PhysicalAssetID { get; set; }
        public string AnalysisUsed { get; set; }
        public string Expiration { get; set; }
        public string Results { get; set; }
        public string ExpectedResults { get; set; }
        public Nullable<int> SampleTest { get; set; }
    
        public virtual BatchProductionRecordEntry BatchProductionRecordEntry1 { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual PhysicalAsset PhysicalAsset { get; set; }
        public virtual SampleTest SampleTest1 { get; set; }
    }
}
