//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SegmentParameter()
        {
            this.SegmentParameter1 = new HashSet<SegmentParameter>();
        }
    
        public int ID { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public Nullable<int> Parameter { get; set; }
        public Nullable<int> OperationsSegment { get; set; }
        public Nullable<int> OpSegmentRequirement { get; set; }
    
        public virtual OperationsSegment OperationsSegment1 { get; set; }
        public virtual OpSegmentRequirement OpSegmentRequirement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentParameter> SegmentParameter1 { get; set; }
        public virtual SegmentParameter SegmentParameter2 { get; set; }
    }
}
