//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentRequirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SegmentRequirement()
        {
            this.ConsumableExpectedRequirement = new HashSet<ConsumableExpectedRequirement>();
            this.EquipmentRequirement = new HashSet<EquipmentRequirement>();
            this.MaterialConsumedRequirement = new HashSet<MaterialConsumedRequirement>();
            this.MaterialProducedRequirement = new HashSet<MaterialProducedRequirement>();
            this.MaterialRequirement = new HashSet<MaterialRequirement>();
            this.PersonnelRequirement = new HashSet<PersonnelRequirement>();
            this.PhysicalAssetRequirement = new HashSet<PhysicalAssetRequirement>();
            this.SegmentRequirement11 = new HashSet<SegmentRequirement>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductSegmentID { get; set; }
        public Nullable<int> ProcessSegmentID { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> EarliestStartTime { get; set; }
        public Nullable<System.DateTime> LatestEndTime { get; set; }
        public string Duration { get; set; }
        public Nullable<int> ProductionParameter { get; set; }
        public Nullable<int> SegmentRequirement1 { get; set; }
        public string RequiredByRequestedSegmentResponce { get; set; }
        public string SeqmentState { get; set; }
        public Nullable<int> ProductionRequest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumableExpectedRequirement> ConsumableExpectedRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentRequirement> EquipmentRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialConsumedRequirement> MaterialConsumedRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProducedRequirement> MaterialProducedRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialRequirement> MaterialRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelRequirement> PersonnelRequirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetRequirement> PhysicalAssetRequirement { get; set; }
        public virtual ProcessSegment ProcessSegment { get; set; }
        public virtual ProductionParameter ProductionParameter1 { get; set; }
        public virtual ProductionRequest ProductionRequest1 { get; set; }
        public virtual ProductSegment ProductSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentRequirement> SegmentRequirement11 { get; set; }
        public virtual SegmentRequirement SegmentRequirement2 { get; set; }
    }
}
