//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SegmentResponse()
        {
            this.ConsumableActual = new HashSet<ConsumableActual>();
            this.EquipmentActual = new HashSet<EquipmentActual>();
            this.MaterialActual = new HashSet<MaterialActual>();
            this.MaterialConsumedActual = new HashSet<MaterialConsumedActual>();
            this.MaterialProducedActual = new HashSet<MaterialProducedActual>();
            this.PersonnelActual = new HashSet<PersonnelActual>();
            this.PhysicalAssetActual = new HashSet<PhysicalAssetActual>();
            this.ProcessSegment = new HashSet<ProcessSegment>();
            this.ProductionData = new HashSet<ProductionData>();
            this.ProductSegment = new HashSet<ProductSegment>();
            this.SegmentResponse11 = new HashSet<SegmentResponse>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public Nullable<int> SegmentResponse1 { get; set; }
        public string RequiredByRequestedSegmentResponse { get; set; }
        public string SegmentState { get; set; }
        public Nullable<int> ProductionRequest { get; set; }
        public Nullable<int> ProductionResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumableActual> ConsumableActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentActual> EquipmentActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialActual> MaterialActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialConsumedActual> MaterialConsumedActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProducedActual> MaterialProducedActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelActual> PersonnelActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssetActual> PhysicalAssetActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessSegment> ProcessSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionData> ProductionData { get; set; }
        public virtual ProductionRequest ProductionRequest1 { get; set; }
        public virtual ProductionResponse ProductionResponse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSegment> ProductSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentResponse> SegmentResponse11 { get; set; }
        public virtual SegmentResponse SegmentResponse2 { get; set; }
    }
}
