//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int ID { get; set; }
        public int RecipeElementID { get; set; }
        public string RecipeElementVersion { get; set; }
        public string Description { get; set; }
        public int ProcedureLogic { get; set; }
    
        public virtual ProcedureLogic ProcedureLogic1 { get; set; }
        public virtual RecipeElement RecipeElement { get; set; }
    }
}
