//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagSpecification
    {
        public int TagIndex { get; set; }
        public string DataType { get; set; }
        public string UnitOfMeasure { get; set; }
        public string DataSource { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> PhysicalAssetID { get; set; }
        public string ProceduralElementReference { get; set; }
        public string Deadband { get; set; }
        public string SignificantDigits { get; set; }
        public string DataCompression { get; set; }
        public string SamplingType { get; set; }
        public Nullable<int> DataSet { get; set; }
    
        public virtual DataSet DataSet1 { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual PhysicalAsset PhysicalAsset { get; set; }
    }
}
