//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDataTypes
    {
        public int ID { get; set; }
        public string f_nvarchar { get; set; }
        public Nullable<System.DateTimeOffset> f_datetime { get; set; }
        public Nullable<System.DateTime> f_date { get; set; }
        public Nullable<float> f_real { get; set; }
        public Nullable<bool> f_bit { get; set; }
        public byte[] f_varbinary { get; set; }
        public string new_field { get; set; }
    }
}
