//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToID()
        {
            this.DirectedLink = new HashSet<DirectedLink>();
        }
    
        public int ID { get; set; }
        public int ToIDValue { get; set; }
        public string ToType { get; set; }
        public string IDScope { get; set; }
        public Nullable<int> Link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DirectedLink> DirectedLink { get; set; }
        public virtual Link Link1 { get; set; }
    }
}
