//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_kep_logger
    {
        public int EquipmentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Controller_ID { get; set; }
        public Nullable<float> Weight_VALUE { get; set; }
        public Nullable<System.DateTime> Weight_TIMESTAMP { get; set; }
        public Nullable<bool> Weight_OK_Value { get; set; }
    }
}
