//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ProductionParameter_Files
    {
        public Nullable<System.Guid> ID { get; set; }
        public Nullable<int> ProductSegmentID { get; set; }
        public Nullable<int> ProcessSegmentID { get; set; }
        public string Parameter { get; set; }
        public Nullable<int> PropertyType { get; set; }
        public string FileType { get; set; }
        public byte[] Data { get; set; }
    }
}
