//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PrintProperties
    {
        public Nullable<System.Guid> ID { get; set; }
        public Nullable<int> ProductionResponse { get; set; }
        public int ClassPropertyID { get; set; }
        public string TypeProperty { get; set; }
        public string NameProperty { get; set; }
        public string ValueProperty { get; set; }
    }
}
