//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowSpecificationConnectionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowSpecificationConnectionType()
        {
            this.WorkflowSpecificationConnection = new HashSet<WorkflowSpecificationConnection>();
            this.WorkflowSpecificationProperty = new HashSet<WorkflowSpecificationProperty>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> WorkflowSpecificationType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowSpecificationConnection> WorkflowSpecificationConnection { get; set; }
        public virtual WorkflowSpecificationType WorkflowSpecificationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowSpecificationProperty> WorkflowSpecificationProperty { get; set; }
    }
}
