//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAlert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkAlert()
        {
            this.WorkAlertProperty = new HashSet<WorkAlertProperty>();
        }
    
        public int ID { get; set; }
        public string MessageText { get; set; }
        public string TimeStamp { get; set; }
        public string Priority { get; set; }
        public string Category { get; set; }
        public Nullable<int> WorkAlertInformation { get; set; }
    
        public virtual WorkAlertInformation WorkAlertInformation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkAlertProperty> WorkAlertProperty { get; set; }
    }
}
