//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowSpecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowSpecification()
        {
            this.WorkflowSpecificationConnection = new HashSet<WorkflowSpecificationConnection>();
            this.WorkflowSpecificationNode = new HashSet<WorkflowSpecificationNode>();
        }
    
        public int ID { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public Nullable<int> WorkflowSpecificationInformation { get; set; }
    
        public virtual WorkflowSpecificationInformation WorkflowSpecificationInformation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowSpecificationConnection> WorkflowSpecificationConnection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowSpecificationNode> WorkflowSpecificationNode { get; set; }
    }
}
