//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkMasterCapability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkMasterCapability()
        {
            this.OpEquipmentCapability = new HashSet<OpEquipmentCapability>();
            this.OpMaterialCapability = new HashSet<OpMaterialCapability>();
            this.OpPersonnelCapability = new HashSet<OpPersonnelCapability>();
            this.OpPhysicalAssetCapability = new HashSet<OpPhysicalAssetCapability>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> WorkMasterID { get; set; }
        public string CapabilityType { get; set; }
        public string Reason { get; set; }
        public Nullable<int> HierarchyScope { get; set; }
        public Nullable<System.DateTimeOffset> StartTime { get; set; }
        public Nullable<System.DateTimeOffset> EndTime { get; set; }
        public Nullable<int> WorkCapability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpEquipmentCapability> OpEquipmentCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpMaterialCapability> OpMaterialCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPersonnelCapability> OpPersonnelCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpPhysicalAssetCapability> OpPhysicalAssetCapability { get; set; }
        public virtual WorkCapability WorkCapability1 { get; set; }
        public virtual WorkMaster WorkMaster { get; set; }
    }
}
