//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkResponse()
        {
            this.JobResponse = new HashSet<JobResponse>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string WorkType { get; set; }
        public Nullable<int> WorkRequestID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ResponseState { get; set; }
        public Nullable<int> WorkPerfomence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobResponse> JobResponse { get; set; }
        public virtual WorkPerformance WorkPerformance { get; set; }
        public virtual WorkRequest WorkRequest { get; set; }
    }
}
