//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowSpecificationConnection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowSpecificationConnection()
        {
            this.WorkflowSpecificationProperty = new HashSet<WorkflowSpecificationProperty>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public int ConnectionType { get; set; }
        public string FromNodeID { get; set; }
        public string ToNodeID { get; set; }
        public Nullable<int> WorkflowSpecification { get; set; }
    
        public virtual WorkflowSpecification WorkflowSpecification1 { get; set; }
        public virtual WorkflowSpecificationConnectionType WorkflowSpecificationConnectionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowSpecificationProperty> WorkflowSpecificationProperty { get; set; }
    }
}
