//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowSpecificationProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowSpecificationProperty()
        {
            this.WorkflowSpecificationProperty1 = new HashSet<WorkflowSpecificationProperty>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string PropertyType { get; set; }
        public string Value { get; set; }
        public Nullable<int> Property { get; set; }
        public Nullable<int> WorkflowSpecificationNode { get; set; }
        public Nullable<int> WorkflowSpecificationNodeType { get; set; }
        public Nullable<int> WorkflowSpecificationConnection { get; set; }
        public Nullable<int> WorkflowSpecificationConnectionType { get; set; }
    
        public virtual WorkflowSpecificationConnection WorkflowSpecificationConnection1 { get; set; }
        public virtual WorkflowSpecificationConnectionType WorkflowSpecificationConnectionType1 { get; set; }
        public virtual WorkflowSpecificationNode WorkflowSpecificationNode1 { get; set; }
        public virtual WorkflowSpecificationNodeType WorkflowSpecificationNodeType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowSpecificationProperty> WorkflowSpecificationProperty1 { get; set; }
        public virtual WorkflowSpecificationProperty WorkflowSpecificationProperty2 { get; set; }
    }
}
