//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDirective
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkDirective()
        {
            this.JobResponse = new HashSet<JobResponse>();
            this.WorkDirectiveRecord = new HashSet<WorkDirectiveRecord>();
        }
    
        public int WorkMasterID { get; set; }
        public int WorkDirective1 { get; set; }
        public Nullable<int> WorkDefinitionInformation { get; set; }
        public int WorkDefinitionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobResponse> JobResponse { get; set; }
        public virtual WorkDefinition WorkDefinition { get; set; }
        public virtual WorkDefinitionInformation WorkDefinitionInformation1 { get; set; }
        public virtual WorkMaster WorkMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDirectiveRecord> WorkDirectiveRecord { get; set; }
    }
}
